name: to_do
description: To Do Flutter App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.4
  responsive_framework: ^0.1.7
  freezed_annotation: ^2.0.1
  json_annotation: ^4.4.0
  sqflite: ^2.0.2+1
  path_provider: ^2.0.9
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  freezed: ^2.0.2
  json_serializable: ^6.1.6
  flutter_lints: ^1.0.4

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/Proxima-Nova-Bold.otf
          weight: 700
        - asset: assets/fonts/Proxima-Nova-Regular.ttf
          weight: 400
